name: Node.js application start

on:
  push:
    branches: [ "main" ]
  
permissions:
  contents: read
  packages: write 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # Asegura que se descargue todo el historial (opcional)
        fetch-depth: 0
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18"
        
    - name: Install dependencies
      run: |
        npm install

    - name: Ejecutar la app
      run: |
        node app.js
        
    - name: Test with Jest
      run: npm test
        
    - name: simulacion del deploy
      run: |
        echo "simular que se esta desplegando la aplicacion en un servidor"

    - name: construir la imagen de docker
      run: |
        docker build -t ghcr.io/19ramirez/node-app:latest .

    - name: Login en GitHub Container Registry
      run: |
        echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: publicar la imagen
      run: |
        docker push ghcr.io/19ramirez/node-app:latest